### ISSUE TITLE
Init value is wrong

### ISSUE THREAD

**Issue by dnish** [iiroj/use-breakpoint#7]
Hey,
after testing I've noticed, that the init value isn't correct. It's always set to the one which was defined as fallback (tested on the client).

**Comment by iiroj** [comment]
Hello, can you be more specific? Do you mean that if the fallback value is for example `mobile`, and the client application is opened as `desktop`, the initial value will stay as `mobile`? Does it start working after changing the screen size?

**Comment by dnish** [comment]
Hey,
yes correct, in this case, you will get mobile on the first render and desktop on the second render. After changing the screen size, you will also get the correct value. The issue only happens on the first render. So if you do something like this:

```
const BREAKPOINTS = { mobile: 0, tablet: 768, desktop: 1280 };
const CurrentBreakpoint = () => {
  const { breakpoint} = useBreakpoint(BREAKPOINTS, 'mobile');
  console.log(breakpoint);
   return null;
};
```
you will get:

```
mobile
desktop
``` 

Tested on Chrome (Mac) and Safari (iOS)

**Comment by iiroj** [comment]
I think this is the expected behavior. Because the fallback value gets rendered on the server as well, it has to the same for client's initial render. Otherwise React hydration might get confused.

It might be possible to enable this behaviour, though. The initial fallback value is set here:
https://github.com/iiroj/use-breakpoint/blob/master/lib/useBreakpoint.ts#L38
And it's updated the first time here:
https://github.com/iiroj/use-breakpoint/blob/master/lib/useBreakpoint.ts#L61

If we simply ran `updateBreakpoint` inside the `useState` hook, it would get the correct initial value. But then again, it would mess up the ssr/isomorphic usage.

I need to think about it...

**Comment by iiroj** [comment]
I created a Draft PR https://github.com/iiroj/use-breakpoint/pull/8 where the initial value is directly the correct one in cases where `defaultValue` _is not_ set. I think it would be a breaking change if it worked like that in the other case.

Please have a look at the PR and tell me what you think. I'll also create some tests (this is the motivation I needed to take the time to write them up).

**Comment by iiroj** [comment]
I added a new optional parameter in the PR, that enables this behavior. By default `hydrateInitial = true` to keep existing behavior, but by setting it to `hydrateInitial = false`, the hook will now return the actual breakpoint on the first render, even if the default breakpoint is different.

What do you think?
